OFBIZ-13416 - We are seeing the following error on the console while performing the steps shown below:
-- Place a sales order from ecommerce or backend order application

-- Quick Ship Entire Order. On console you will see the below error:

2026-05-20 19:44:56,390 |jsse-nio-8443-exec-7 |ServiceDispatcher             |T| [[ASync service finished...- total:0.0,since last(ASync service sta...):0.0]] - 'order / createShipmentStatus'
2026-05-20 19:44:56,390 |jsse-nio-8443-exec-7 |ServiceDispatcher             |T| Sync service [order/createShipment] finished in [385] milliseconds
2026-05-20 19:44:56,394 |OFBiz-JobQueue-0     |TransactionUtil               |W| Calling transaction setRollbackOnly; this stack trace shows where this is happening:
java.lang.Exception: rollback called in Entity Engine SQLProcessor
at org.apache.ofbiz.entity.transaction.TransactionUtil.setRollbackOnly(TransactionUtil.java:372)
at org.apache.ofbiz.entity.jdbc.SQLProcessor.rollback(SQLProcessor.java:199)
at org.apache.ofbiz.entity.datasource.GenericDAO.insert(GenericDAO.java:117)
at org.apache.ofbiz.entity.datasource.GenericHelperDAO.create(GenericHelperDAO.java:68)
at org.apache.ofbiz.entity.GenericDelegator.create(GenericDelegator.java:903)
at org.apache.ofbiz.entity.GenericValue.create(GenericValue.java:76)
at org.apache.ofbiz.service.engine.EntityAutoEngine.invokeCreate(EntityAutoEngine.java:378)
at org.apache.ofbiz.service.engine.EntityAutoEngine.runSync(EntityAutoEngine.java:124)
at org.apache.ofbiz.service.ServiceDispatcher.runSync(ServiceDispatcher.java:429)
at org.apache.ofbiz.service.ServiceDispatcher.runSync(ServiceDispatcher.java:244)
at org.apache.ofbiz.service.GenericDispatcherFactory$GenericDispatcher.runSync(GenericDispatcherFactory.java:77)
at org.apache.ofbiz.service.job.GenericServiceJob.exec(GenericServiceJob.java:77)
at org.apache.ofbiz.service.job.AbstractJob.run(AbstractJob.java:106)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
at java.base/java.lang.Thread.run(Thread.java:840)
2026-05-20 19:44:56,395 |OFBiz-JobQueue-0     |GenericDelegator              |E| Failure in create operation for entity [ShipmentStatus]: org.apache.ofbiz.entity.GenericEntityException: Error while inserting: [GenericEntity:ShipmentStatus][changeByUserLoginId,admin(java.lang.String)][createdStamp,2026-05-20 19:44:56.39(java.sql.Timestamp)][createdTxStamp,2026-05-20 19:44:56.39(java.sql.Timestamp)][lastUpdatedStamp,2026-05-20 19:44:56.39(java.sql.Timestamp)][lastUpdatedTxStamp,2026-05-20 19:44:56.39(java.sql.Timestamp)][shipmentId,10000(java.lang.String)][statusDate,2026-05-20 19:44:56.39(java.sql.Timestamp)][statusId,SHIPMENT_INPUT(java.lang.String)] (SQL Exception while executing the following:INSERT INTO OFBIZ.SHIPMENT_STATUS (STATUS_ID, SHIPMENT_ID, STATUS_DATE, CHANGE_BY_USER_LOGIN_ID, LAST_UPDATED_STAMP, LAST_UPDATED_TX_STAMP, CREATED_STAMP, CREATED_TX_STAMP) VALUES (?, ?, ?, ?, ?, ?, ?, ?) (Referential integrity constraint violation: "SHPMNT_STTS_SHMT: OFBIZ.SHIPMENT_STATUS FOREIGN KEY(SHIPMENT_ID) REFERENCES OFBIZ.SHIPMENT(SHIPMENT_ID) ('10000')"; SQL statement:
INSERT INTO OFBIZ.SHIPMENT_STATUS (STATUS_ID, SHIPMENT_ID, STATUS_DATE, CHANGE_BY_USER_LOGIN_ID, LAST_UPDATED_STAMP, LAST_UPDATED_TX_STAMP, CREATED_STAMP, CREATED_TX_STAMP) VALUES (?, ?, ?, ?, ?, ?, ?, ?) [23506-240])). Rolling back transaction.