Improved: https://localhost:8443/webtools/control/EntityExportAll Added the support of ThruDate on this screen. The user may want to export the data for limited number of days/months/years from this screen.
The current implementation restrict user to enter values only in the fromDate field. And all the records until today gets exported.
Fixed: And also fixed a bug, this screen was failing to export the data and giving error in ServerHit entity, because there is no createdStamp field in this entity.

2026-02-16 11:00:12,962 |sse-nio-8443-exec-24 |ServiceEventHandler           |E| Service invocation error
org.apache.ofbiz.service.GenericServiceException: Service [entityExportAll] target threw an unexpected exception (FieldName createdStamp not found for entity: ServerHit)
	at org.apache.ofbiz.service.engine.StandardJavaEngine.serviceInvoker(StandardJavaEngine.java:118) ~[main/:?]
	at org.apache.ofbiz.service.engine.StandardJavaEngine.runSync(StandardJavaEngine.java:57) ~[main/:?]
	at org.apache.ofbiz.service.ServiceDispatcher.runSync(ServiceDispatcher.java:429) ~[main/:?]
	at org.apache.ofbiz.service.ServiceDispatcher.runSync(ServiceDispatcher.java:244) ~[main/:?]
	at org.apache.ofbiz.service.GenericDispatcherFactory$GenericDispatcher.runSync(GenericDispatcherFactory.java:77) ~[main/:?]
	at org.apache.ofbiz.webapp.event.ServiceEventHandler.invoke(ServiceEventHandler.java:254) [main/:?]
	at org.apache.ofbiz.webapp.control.RequestHandler.runEvent(RequestHandler.java:1086) [main/:?]
	at org.apache.ofbiz.webapp.control.RequestHandler.doRequest(RequestHandler.java:672) [main/:?]
	at org.apache.ofbiz.webapp.control.ControlServlet.handle(ControlServlet.java:231) [main/:?]
	at org.apache.ofbiz.webapp.control.ControlServlet.doPost(ControlServlet.java:81) [main/:?]
	at jakarta.servlet.http.HttpServlet.service(HttpServlet.java:590) [tomcat-servlet-api-10.1.47.jar:6.0]
	at jakarta.servlet.http.HttpServlet.service(HttpServlet.java:658) [tomcat-servlet-api-10.1.47.jar:6.0]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193) [tomcat-catalina-10.1.47.jar:10.1.47]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:138) [tomcat-catalina-10.1.47.jar:10.1.47]
	at org.apache.ofbiz.webapp.control.SameSiteFilter.doFilter(SameSiteFilter.java:45) [main/:?]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:162) [tomcat-catalina-10.1.47.jar:10.1.47]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:138) [tomcat-catalina-10.1.47.jar:10.1.47]
	at org.apache.ofbiz.webapp.control.ContextFilter.doFilter(ContextFilter.java:188) [main/:?]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:162) [tomcat-catalina-10.1.47.jar:10.1.47]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:138) [tomcat-catalina-10.1.47.jar:10.1.47]
	at org.apache.ofbiz.base.util.CacheFilter.doFilter(CacheFilter.java:63) [main/:?]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:162) [tomcat-catalina-10.1.47.jar:10.1.47]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:138) [tomcat-catalina-10.1.47.jar:10.1.47]
	at org.apache.ofbiz.webapp.control.ControlFilter.doFilter(ControlFilter.java:272) [main/:?]
	at jakarta.servlet.http.HttpFilter.doFilter(HttpFilter.java:53) [tomcat-servlet-api-10.1.47.jar:6.0]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:162) [tomcat-catalina-10.1.47.jar:10.1.47]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:138) [tomcat-catalina-10.1.47.jar:10.1.47]
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:165) [tomcat-catalina-10.1.47.jar:10.1.47]
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:88) [tomcat-catalina-10.1.47.jar:10.1.47]
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:482) [tomcat-catalina-10.1.47.jar:10.1.47]
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:113) [tomcat-catalina-10.1.47.jar:10.1.47]
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:90) [tomcat-catalina-10.1.47.jar:10.1.47]
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:72) [tomcat-catalina-10.1.47.jar:10.1.47]
	at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:664) [tomcat-catalina-10.1.47.jar:10.1.47]
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:342) [tomcat-catalina-10.1.47.jar:10.1.47]
	at org.apache.coyote.http2.StreamProcessor.service(StreamProcessor.java:476) [tomcat-coyote-10.1.47.jar:10.1.47]
	at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:63) [tomcat-coyote-10.1.47.jar:10.1.47]
	at org.apache.coyote.http2.StreamProcessor.process(StreamProcessor.java:102) [tomcat-coyote-10.1.47.jar:10.1.47]
	at org.apache.coyote.http2.StreamRunnable.run(StreamRunnable.java:35) [tomcat-coyote-10.1.47.jar:10.1.47]
	at org.apache.tomcat.util.threads.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:975) [tomcat-util-10.1.47.jar:10.1.47]
	at org.apache.tomcat.util.threads.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:493) [tomcat-util-10.1.47.jar:10.1.47]
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:63) [tomcat-util-10.1.47.jar:10.1.47]
	at java.base/java.lang.Thread.run(Thread.java:840) [?:?]
Caused by: java.lang.IllegalArgumentException: FieldName createdStamp not found for entity: ServerHit
	at org.apache.ofbiz.entity.condition.EntityExpr.checkRhsType(EntityExpr.java:214) ~[main/:?]
	at org.apache.ofbiz.entity.condition.EntityExpr.makeWhereString(EntityExpr.java:139) ~[main/:?]
	at org.apache.ofbiz.entity.condition.EntityJoinOperator.addSqlValue(EntityJoinOperator.java:84) ~[main/:?]
	at org.apache.ofbiz.entity.condition.EntityConditionListBase.makeWhereString(EntityConditionListBase.java:80) ~[main/:?]
	at org.apache.ofbiz.entity.condition.EntityConditionList.makeWhereString(EntityConditionList.java:32) ~[main/:?]
	at org.apache.ofbiz.entity.condition.EntityJoinOperator.addSqlValue(EntityJoinOperator.java:84) ~[main/:?]
	at org.apache.ofbiz.entity.condition.EntityConditionListBase.makeWhereString(EntityConditionListBase.java:80) ~[main/:?]
	at org.apache.ofbiz.entity.condition.EntityConditionList.makeWhereString(EntityConditionList.java:32) ~[main/:?]
	at org.apache.ofbiz.entity.datasource.GenericDAO.makeConditionWhereString(GenericDAO.java:956) ~[main/:?]
	at org.apache.ofbiz.entity.datasource.GenericDAO.selectListIteratorByCondition(GenericDAO.java:828) ~[main/:?]
	at org.apache.ofbiz.entity.datasource.GenericHelperDAO.findListIteratorByCondition(GenericHelperDAO.java:171) ~[main/:?]
	at org.apache.ofbiz.entity.GenericDelegator.find(GenericDelegator.java:1652) ~[main/:?]
	at org.apache.ofbiz.entity.util.EntityQuery.queryIterator(EntityQuery.java:411) ~[main/:?]
	at org.apache.ofbiz.webtools.WebToolsServices.entityExportAll(WebToolsServices.java:555) ~[main/:?]
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?]
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.base/java.lang.reflect.Method.invoke(Method.java:568) ~[?:?]
	at org.apache.ofbiz.service.engine.StandardJavaEngine.serviceInvoker(StandardJavaEngine.java:101) ~[main/:?]
	... 42 more
2026-02-16 11:00:12,965 |sse-nio-8443-exec-24 |RequestHandler                |E| Request entityExportAll caused an error with the following message: Error calling event: org.apache.ofbiz.webapp.event.EventHandlerException: Service invocation error (FieldName createdStamp not found for entity: ServerHit)
2026-02-16 11:00:12,966 |sse-nio-8443-exec-24 |RequestHandler                |I| Rendering View