Fixed: Pressing sort button in any UI view will end with NPE (OFBIZ-13378)
Pressing sort button for field ends with error:
java.lang.NullPointerException: Cannot invoke "Object.getClass()"
because "object" is null ControlFilter.java:188

 if ( (object.getClass().equals(String.class) || object instanceof Collection))
 
need to be:
 
if ( object != null && (object.getClass().equals(String.class)
        || object instanceof Collection))

Thanks: Vitaly Repetenko